NatLibFi/ekirjasto-circulation

alembic/versions/20240205_d7ef6948af4e_create_loancheckouts_table.py, api/circulation.py, core/model/__init__.py, core/model/patron.py, tests/api/test_circulationapi.py
Context found at https://jira.lingsoft.fi/browse/SIMPLYE-195
=> Implement LoanCheckout model for gathering history

api/admin/config.py
Upgrade ekirjasto-circulation-admin to [v0.1.0](https://github.com/NatLibFi/ekirjasto-circulation-admin/releases/tag/v0.1.0) with latest changes
=> Upgrade ekirjasto-circulation-admin to v0.1.0

api/ekirjasto_authentication.py, api/ekirjasto_controller.py, api/problem_details.py, api/routes.py, tests/api/finland/test_ekirjasto.py
Added endpoints to call "/passkey/register" endpoints at ekirjasto API on behalf of the enduser. Implementation was done so that it is easy to add more similar endpoints later.
The mobile client doesn't have ekirjasto token in usable form, "/passkey/register" endpoints requires those to authenticate requests.
See more at issue: SIMPLYE-218
- New unit tests for ekirjasto authentication were created. And tested manually with curl command.
=> SIMPLYE-218 Passkey endpoints

core/lane.py, tests/api/feed/test_opds_acquisition_feed.py, tests/api/test_lanes.py, tests/core/test_lane.py
When selecting the 'All' option under language facet, the search was being performed only against languages defined for the library instead of all the languages in the collection.
Now it should will show books in any language that exists in the collection.
=> Fix search filter for 'All' languages facet

alembic/versions/20240222_9966f6f95674_create_admincredentials_table.py, api/admin/config.py, api/admin/controller/base.py, api/admin/controller/individual_admin_settings.py, api/admin/controller/library_settings.py, api/admin/controller/reset_password.py, api/admin/controller/sign_in.py, api/admin/controller/view.py, api/admin/ekirjasto_admin_authentication_provider.py, api/admin/routes.py, api/admin/templates.py, api/ekirjasto_authentication.py, core/model/admin.py, tests/api/admin/controller/test_sign_in.py, tox.ini
Implement admin authentication via external E-kirjasto authentication application.
This implementation assumes that:
- The users & roles are managed externally, not with circulation.
- The system will have only one library, so the external users will be mapped as site-wide admins. See table below.
| Circulation admin role | E-kirjasto role | Description (fi) | Description (en)
|---|---|---|---|
| _unauthorized_ | `sysadmin` | - | Internal technical role for auth E-kirjasto auth system management only |
| `system-admin` | `orgadmin` | E-kirjaston pääkäyttäjä | E-library main admin |
| `manager-all` | `admin` | Paikalliskirjaston pääkäyttäjä | Local library admin user |
| _unauthorized_ | `registrant` | Paikalliskirjaston työntekijä / rekisteröijä | Local librarian user / registering agent …
=> Enable authentication with suomi.fi credentials

.github/workflows/test-build.yml, README.md, docker-compose.yml, docker/Dockerfile
This PR enables the docker image builds in GitHub Actions for `ekirjasto-circ-scripts`, `ekirjasto-circ-exec` and `ekirjasto-circ-webapp` to be used in deployment.
=> Enable Docker image builds in Actions

alembic/versions/20240321_4915a361b082_add_duration_to_circulationevents.py, api/circulation.py, api/opensearch_analytics_provider.py, api/s3_analytics_provider.py, core/local_analytics_provider.py, core/model/circulationevent.py, tests/api/test_circulationapi.py
This PR adds duration field to circulation events (database, OpenSearch, S3). It is used to store loan duration times (in seconds) to loan revoke events.
This adds new duration field to circulationevent model and OpenSearch event index. OpenSearch mapping change is a small addition and it is done in lightweight ad-hoc manner as currently we don't have flow for migrating from mapping version to another.
Loan durations cannot be added retroactively to the existing events since we didn't have this data earlier.
Loan duration enables filtering out short loans from analytics (https://jira.lingsoft.fi/browse/SIMPLYE-181). This implementation will be its own PR.
I tested the local analytics events and OpenSearch events with Palace Bookshelf open access books and revoke events have correct …
=> Add duration field to circulation events

docker/Dockerfile
Run the `util/compile_translations` script during image build to compile the `.po` files into `.mo` files.
The script requires PALACE_SEARCH_URL to be defined, even though it doesn't use it.
[SIMPLYE-269](https://jira.lingsoft.fi/browse/SIMPLYE-269) - Integrate translation files from Transifex into the Circulation image build
=> Compile translations during webapp image build

alembic/versions/20240404_be8ed331efcc_add_last_signed_in_column_to_.py, api/admin/controller/sign_in.py, core/model/admin.py, core/monitor.py
New reaper monitor created for deleting externally authenticated admin users with over 180 days since last login.
A new column `last_signed_in` added in `admincredentials` table. This field is updated each time an admin signs in.
This reaper is registered as part of the already existing `bin/database_reaper` script, which is run once per day.
<https://jira.lingsoft.fi/browse/SIMPLYE-226> - Clean inactive e-kirjasto admins from circulation DB
=> Create reaper monitor for deleting inactive admins

api/admin/controller/library_settings.py, api/admin/controller/sign_in.py, api/admin/ekirjasto_admin_authentication_provider.py, api/ekirjasto_authentication.py, api/ekirjasto_consortium.py, bin/ekirjasto_consortium_monitor, core/configuration/library.py, core/model/library.py, docker/services/cron/cron.d/circulation, tests/api/admin/controller/test_collections.py, tests/api/admin/controller/test_sign_in.py, tests/api/test_selftest.py, tests/core/models/test_work.py, tests/core/test_ekirjasto_consortium_monitor.py, tests/core/test_external_search.py, tests/core/test_scripts.py
- Possibility to customize lanes for each Kimppa (aka consortium)
- All Kimppas share the same collections, i.e.:
-> License pools shared between all Kimppas
-> All patrons will have access to the same works regardless of Kimppa
- Easy handling for municipality and Kimppa data and mapping. Mapping done based on municipality code received during sign in.
1) Municipality code for patron and admin during authentication
2) Two 3rd party APIs:
- Kirkanta, <https://api.kirjastot.fi/>
- Provides list of cities and Kimppas
- Kansallinen koodistopalvelu, <https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=362&versionKey=440>
- Provides list of municipality codes and names. The authentication system uses these codes to define the users' municipality
- …
=> SIMPLYE-261 - Municipality and consortium management

api/admin/controller/library_settings.py, api/ekirjasto_consortium.py, core/configuration/library.py
- Fix typo and improve wording under library settings
- Add validation for municipality codes under library settings
- Synchronize municipalities when saving a library so there is no need to wait for the cron job
- Add 1 hour cache to Kirkanta and Koodistopalvelu API calls
<https://jira.lingsoft.fi/browse/SIMPLYE-263> - Implement custom lane management for local librarians
=> Improve consortium management

alembic/versions/20240405_b28ac9090d40_add_apitoken_model.py, core/model/__init__.py, core/model/apitokens.py
This PR adds apitokens table to the database to be used by [E-kirjasto Data API](https://github.com/NatLibFi/ekirjasto-data-api).
https://jira.lingsoft.fi/browse/SIMPLYE-292
=> Add apitokens table to database for E-kirjasto Data API

api/authentication/base.py, api/ekirjasto_authentication.py
The current logic is flawed in that it does not recognize if a patron has already signed in and been assigned to a library. When authenticating, the patron lookup is filtered by library id (of the default library), and the existing patron is not found.
Now changed to search for patrons within any library so it finds (and updates) the existing patron instead of trying to create a duplicate.
This issue was introduced in an earlier PR (<https://github.com/NatLibFi/ekirjasto-circulation/pull/30>).
=> Fix library ID handling during patron auth

api/controller/base.py
Each patron is assigned one library based on municipality. The clients are currently sending all requests towards the default library. For patrons assigned to a library, this fails due to authorization. 
The clients don't need to have access to multiple libraries so we can just override the library for the requests coming from authenticated patrons.
The alternative would be to make the clients choose the library based on the authentication response.
=> Override library for authenticated patron requests

api/ekirjasto_controller.py
Related to the issue SIMPLYE-305, endpoint was returning http code 400 when circulation token is not present in the header. Instead correct http code to return is 401.
=> Return 401 if the circulation token is not present in the header.

api/controller/circulation_manager.py
The licensepool query for patron `/borrow` endpoint does not include collections from the default library, resulting in the following error when patron tries to borrow books:
`WARNING problem_detail.py "The item you're asking about (ISBN/9789515246646) isn't in this collection."`
This commit changes the query to include the collections from the default library.
<https://jira.lingsoft.fi/browse/SIMPLYE-263> - Implement custom lane management for local librarians
=> Fix borrowing for patrons in a consortium

core/entrypoint.py, tests/core/models/test_library.py
Enable all entrypoints (i.e. eBooks/All/Audiobooks) by default when creating a new library.
<https://jira.lingsoft.fi/browse/SIMPLYE-329> - Audiobooks are not available in Kimppa collections
=> Enable all entrypoints by default

api/admin/controller/library_settings.py, api/controller/circulation_manager.py, api/lanes.py, core/lane.py, tests/api/admin/controller/test_lanes.py, tests/api/controller/test_scopedsession.py, tests/api/test_lanes.py, tests/core/models/test_library.py, tests/core/test_lane.py, tests/core/test_scripts.py, tests/fixtures/api_controller.py, tests/fixtures/database.py
Allow system admins to centrally manage a default set of lanes. 
- Lanes defined for the default library are shown for all other libraries.
- Custom lanes defined for a library will show up on top of the lane catalog.
- Resetting lanes for any other than default library just deletes all lanes without generating new ones.
- The library will still show lanes from default library after reset.
- Authorization rules changed to allow user from any library to fetch lanes from default library.
<https://jira.lingsoft.fi/browse/SIMPLYE-320> - Default test user from Suomi.fi cannot see lanes defined by the system administrator
=> Show default library lanes for all libraries

api/admin/controller/lanes.py
Continuation for https://github.com/NatLibFi/ekirjasto-circulation/pull/55
The lanes in other libraries are prioritized and shown before the lanes in default library.
=> Show non-default library lanes on top

core/search/document.py, core/search/v5.py
Adjust OpenSearch work index mappings' sort_title and sort_author analyzers to correctly sort scandinavian alphabet.
https://jira.lingsoft.fi/browse/SIMPLYE-345
=> Adjust search sort field analyzers to work with scandinavian letters

core/configuration/library.py, core/model/library.py, tests/api/admin/controller/test_library.py, tests/api/test_authenticator.py, tests/api/test_circulationapi.py, tests/core/models/test_library.py, tests/fixtures/library.py
Other libraries now inherit any unset setting value from the default library.
Also, add new options to show/hide library settings in UI based on whether the library is the default or not. This allows:
- Hiding the Kirkanta synchronization panel from default library.
- Showing Filter&lane panel only for default library.
- Hiding settings that don't need to be customized per Kimppa library.
The support e-mail and website are now optional to allow leaving those empty for Kimppa libraries.
<https://jira.lingsoft.fi/browse/SIMPLYE-354> - Improve library settings handling
=> Inherit settings from default library

api/lanes.py, tests/api/test_lanes.py
Give default lanes lower priority when creating default set of lanes to make the Kimppa specific curated lanes show up on top.
The endpoint for updating lane ordering was already handled in an earlier PR, but missed the case of initial lane creation and RESET.
=> Give default lanes lower priority when creating default set of lanes

core/lane.py
This is an attempt to fix an issue with empty search results for initial top level lane catalog.
Seems like the join might cause issues with the expunge/merge logic used to load top level lanes.
=> Remove join from top level lane query

core/lane.py, tests/core/test_app_server.py, tests/core/test_lane.py
Accept-Language header check seems to cause inconsistencies in top-level search. Also, we handle languages as facets in search.
https://jira.lingsoft.fi/browse/SIMPLYE-388
=> Ignore Accept-Language header in search results

core/classifier/keyword.py, tests/core/classifiers/test_keyword.py
Add "poetry" to fiction classifier indicators.
https://jira.lingsoft.fi/browse/SIMPLYE-410
An assert added to test_keyword to check that "Poetry" as keyword makes is_fiction classification true.
=> Classify poetry under fiction

api/controller/patron_auth_token.py, tests/api/controller/test_patron_access_token.py
This PR increases the duration of patron auth token to one week so that patrons don't have to sign in so frequently.
=> EKIR-208 Change token expiration

docker/services/nginx/nginx.conf, docker/services/uwsgi/uwsgi.d/60_processes.ini
- Increase nginx worker_connections from 768 -> 4096
- Increase uwsgi process count 3 -> 6
Tests fails, because of unmerged fixes, and unaccessible resource for json schema validation:
Work in progress...
```
url = 'https://readium.org/webpub-manifest/schema/extensions/presentation/metadata.schema.json
```
=> increased nginx worker connections & uwsgi processes

api/odl2.py
Change operators back to how they were before since the change didn't have the effect they thought should have.
=> Change operators > back to >=

core/resources/opds2_schema/readium-metadata.schema.json
Url for opds2 presentation hints schema has changed, hence url updated.
Local core tests passes.
api tests fixed in https://github.com/NatLibFi/ekirjasto-circulation/pull/89
=> updated opds presentation hints schema url

api/circulation.py, api/circulation_exceptions.py, api/controller/loan.py, api/problem_details.py, tests/api/controller/test_loan.py, tests/api/test_circulationapi.py
Circulation will give response 502 NoAvailableCopiesWhenReserved when a patron tries to checkout a loan that was "reserved" for them but turns out not to be available. Their hold is updated with a new end date.
When the patron was at the top of a license pool's hold queue and at their hold limit, circulation gave response 403 that they had reached their hold limit when they tried to checkout a presumably (and notified) available license. This was, based on comments and tests, a by design functionality.
When a patron tries to loan/hold a book, the request goes to route "/works/<identifier_type>/<path:identifier>/borrow" and the process loan.py <-> circulationapi.py <-> odl.py.
This PR changes functionality:
- 403 PatronHoldLimitReached is not raised in enforce_limits() when a patron is not …
=> Ekir 213 enable loan when not at loan limit

api/local_analytics_exporter.py
- Modified list comprehension to safely handle missing or None 'contributors'
- Use .get() with default empty list and 'or []' to ensure valid input for len()
- Prevents TypeError when calculating max length of contributors lists
Tested with falsy database
REF: [EKIR-382]
=> Fix max_contribs calculation to handle None values

docker/services/cron/cron.d/circulation
Updates scripts so that import has been done before lists and lanes are updated. 
Import xx:30
Lists xx:45
Lanes xx:55
And auto-update now runs office hours 8-16 hourly manner.
Also notifications are now run every four hours starting from 08:00.
We'll see how it goes...
=> Update circulation timed scripts

core/classifier/bisac.py, core/model/classification.py, tests/core/classifiers/test_bisac.py
Classify Poetry as Fiction.
Poetry was classified as None. These changes classify Poetry as fiction except if it's a subclass of something non-fiction. Note though, that our test feed does not have any book with a BISAC code where Poetry is a subclass of a non-fiction book so this behaviour can only be observed in unit tests.
Unit testing and local backend testing (run opds_import_monitor, check results in opensearch dashoard).
=> EKIR-389 Classify poetry as fiction

api/lanes.py, core/classifier/__init__.py, core/classifier/bisac.py, core/classifier/keyword.py, tests/api/finland/test_loan_excel_export.py, tests/core/classifiers/test_keyword.py, tests/core/test_external_search.py
Replace Literary Fiction with General Fiction.
Literary Fiction isn't a preferred classification name so it needed to be replaced with General Fiction instead.
Unit tests and checking imported collection locally with pgadmin. Screenshot in the Jira ticket.
=> EKIR-380 Replace Literary with General

api/local_analytics_exporter.py, tests/api/finland/test_loan_excel_export.py
Added Fiction/on-fiction row to excel exporter
[EKIRJASTO-20](https://jira.it.helsinki.fi/browse/EKIRJASTO-20)
Tested on local circulation instance using development environment databases.
- [x ] All new and existing tests passed.
=> Ekirjasto 20 excel export: add "isfiction" classification to report

core/metadata_layer.py, core/model/contributor.py, core/opds2_import.py, tests/core/files/opds2/feed.json, tests/core/test_opds2_import.py
If an OPDS2 feed publication has an `author` but the `name` value in `null`, import the author's name as `[Unknown]` to Circulation.
When the name of a contributor was missing, it raised an error which prevented a book's import into Circulation. This PR changes the functionality so that 
- When a name property of a webpub_manifest_parser Contributor object is missing, the missing properties are saved as `[Unknown]` values into Circulation's contributor data.
- Since the missing properties caused an error during the parser's extraction, that error is no longer recorded as a coverage fail which lead to the book not being imported to Circulation.
- The functionality for edited books without an author is kept intact.
Based on unit tests since our test feed doesn't contain an appropriate item.
=> Ekir 384 handle null contributor names

core/opds_import.py, tests/core/test_opds_import.py
This PR adds information to log a message about OPDS feed titles that fail during import.
When an OPDS feed is imported, it logs information about how many titles are imported and how many fail. However, it does not log what titles fail and what causes them to fail. 
The log message in the admin UI in admin/web/troubleshooting/diagnostics/monitor under odl2 import monitor now shows which ISBNs fail and any recorded error message.
Tested locally with new feed that contains one failing title.
=> Ekirjasto 18 show failed items during opds import

core/classifier/__init__.py, core/metadata_layer.py
Re-classify (assign a genre to a subject) imported works always.
Genres for a work were not updated despite changing the assignment of a new genre for a subject. This was due to two things: During OPDS import, existing subjects were considered ok, and secondly that a subject once assigned to a genre was considered final. The code now marks each work subjects to be marked for classification, and forces each subject to go through subject-genre assignment.
Local circ:
- Database checks of genres and subjects (and lanes) for works after OPDS import and work_classification script runs.
=> EKIR-220 Enable classification always

core/classifier/__init__.py, core/classifier/bisac.py, core/model/classification.py, core/model/work.py, docker-compose-dev.yml, tests/core/classifiers/test_bisac.py, tests/core/classifiers/test_classifier.py, tests/core/models/test_work.py
Feedbooks BISAC codes with postfix "N" are now mapped to circulation's BISAC codes.
Some BISAC subjects are mapped to their appropriate genres (comics, autobiographies, general fiction).
Fiction status is reassessed when assessing all found genres. If a work only has one genre, the fiction status will be determined by that genre's fiction status.
Calculating genre weights is left out in most part of the code now.
Also, commiting our docker compose file for development so it's available for everyone.
We had noticed that a lot of works were missing genre(s) despite having BISAC codes in the feed, and that their fiction status was either None or incorrect. After these fixes, there's only some juvanile and YA works still missing genres but we'll address those in later PRs.
Locally …
=> Recalculate fiction and genres

core/classifier/bisac.py, tests/core/classifiers/test_bisac.py
Feedbooks subjects were passed on to keyword classifier which could lead to unwanted results. Disable it when resolving fiction and genre.
We only want to use BISAC codes for determining genres and fiction status to avoid guessing them.
Locally comparing with previous classification results. Fiction status was not affected but genres were (for ~100 works).
=> Ekir 240 disable keyword classifier

core/model/licensing.py, tests/api/test_odl.py, tests/api/test_odl2.py, tests/core/models/test_licensing.py
This is the direct implementation of Palace project's [Update license pools for ODL licenses that are loan + concurrency limited](https://github.com/ThePalaceProject/circulation/pull/2085/files#top) fix. For loan limited licensepools, the code was only checking the amount of `checkouts_left` and not `concurrency`. It now returns the minimum of those.
Users were given false information about a book's availability: the app showed the book was loanable (because there were checkouts left) but when they tried to loan it, it turned into a hold (because all the licenses were checked out and concurrent users had been reached).
Locally and unit tests.
=> Ekir 197 handle loan and concurrency limited licensepools

api/controller/loan.py, api/odl.py, api/opds_for_distributors.py, api/overdrive.py, core/opds2_import.py, core/opds_import.py, core/util/http.py, customlists/customlist_import.py, tests/api/files/odl/unavailable.json, tests/api/mockapi/mock.py, tests/api/test_odl.py, tests/api/test_opds_for_distributors.py, tests/core/test_opds_import.py, tests/core/util/test_http.py, tests/fixtures/odl.py
Handle the case where we think there are available licenses, but when we reach out to the content provider, it turns out there are no licenses available.
We were getting a lot of 502 responses with no specific debugging info. It turned out that the content provider was responding with a `application/api-problem+json` and not a `application/problem+json` when there were no copies left when trying to checkout a book. The relevant code is in `api/odl.py`.
This PR implements [OPDS2 + ODL Handle case where no licenses are available ](https://github.com/ThePalaceProject/circulation/pull/2057) solution together with their [Refactor BadResponseException](https://github.com/ThePalaceProject/circulation/pull/2034).
During the implementation, some needed refactoring of how HTTP responses in general …
=> Ekir 219 handle 502 errors when loaning

.gitignore, bin/informational/license_report, core/scripts.py, scripts.py
New `license_report` script that can be run to check the status of all our licenses.
We have renewed licenses that act unexpectedly. Before we make any fixes, let's take a look at what information circulation has of those licenses.
Locally.
In your local `scripts` container, run:
`../core/bin/run informational/license_report`
and read the log.
To see the updated `explain` script run e.g.:
`../core/bin/run informational/explain --identifier-type="ISBN" 9789510482926`
and read the log.
****
=> Ekir 289 explain licenses in licensepool

core/metadata_layer.py, tests/core/test_circulation_data.py
Set all removed licenses to status "unavailable".
Old licenses have been used for loans because circulation has had outdated information about them. This is due to the Licenses Info Documents having inaccurate information about `checkouts_left`. The licenses had actually reached their loan limit and they had been removed from the feed. But because circulation reads the details from License Info Documents during each import to be in sync with the provider, and since that information could not have been read due to removing the licenses, the licenses were left as valid ones to be used for loans.
Setting removed licenses to be "unavailable" will cause them to be ignored for loan checkouts and statistics.
Unit test.
=> Ekir 299 set removed license as unavailable

core/scripts.py, scripts.py
Add the collection and patron hold queue information to `license_report` script, and license status to `explain`.
Collection name can help filter results when reviewing the data.
Checking the hold queue amount is important.
Locally.
=> More details to scripts

scripts.py
Add the work title and identifier to license rows as well. Add `is_missing` and `last_checked` information to each license.
If we run into trouble with our licenses again, this information will let us know if any licenses are missing or when it's been last checked.
Locally ran the report.
=> Add the is_missing and last_checked to report

api/controller/odl_notification.py, api/lcp/status.py, api/odl.py
Make Links an optional field in Loan Status Document.
Missing Links field caused a validation error when getting ODL loan notification requests. It should be a MUST field according to https://readium.org/lcp-specs/releases/lsd/latest.html#25-links but make it optional for now.
Can't really be tested locally, only in our test environment.
=> Make Links optional

api/odl.py, core/scripts.py, core/util/notifications.py, tests/api/test_odl.py, tests/core/util/test_notifications.py
Hardcode notification texts into Finnish for now. Loan notifications should be sent 3 and 1 days before expiry.
To enable the quick release of push notifications, using Finnish texts is the fastest way until we figure out how to translate the notifications.
Tests.
=> Ekir 427 push notification texts to finnish

api/odl.py, core/model/licensing.py
Add license pool information in our logs so that we can identify license pool specific problems more easily.
We noticed some failing downloads where the license id is missing in the fulfill content link. Without the license pool information, we can't identify which title this problem occurs with.
Locally.
=> Add license pool logging

.github/actions/poetry/action.yml, .github/workflows/test-build.yml, docker/ci/test_scripts.sh
This updates Docker workflows. The most significant change is to use `docker/bake-action` for building and loading images.
* [`.github/workflows/test-build.yml`](diffhunk://#diff-a583f7935a5f3192471a2999cbf059eadc857228b5be2c7247f481b799949f8dL290-R316): Replaced the `docker compose up --build` command with `docker/bake-action` to build and load Docker Compose images, enabling better caching and separation of build and runtime steps. Added detailed build arguments and caching configurations for improved efficiency.
* [`docker/ci/test_scripts.sh`](diffhunk://#diff-3c04cc2198529b239e55658e46a0c2e82b8935fda4c471d259049cbb295e379cL16-R17): Removed database initialization log checks, as health checks are now implicitly handled by `docker compose up -d`.
=> Github workflow updates

api/odl2.py
Only a loan with a license can be checked in.
The loan reaper script crashed because prod had loans not associated with a license. Obviously it's possible that loans can be associated with a license pool instead of a license.
The original script was collection-based so `collection.id` was added to the query so that the logs make more sense.
Basically the already existing `test_run_once` would have duplication if a license pool loan was implemented so decided not to add anything.
=> Checkin loan license
